### ISSUE TITLE
Interface "Magento\Elasticsearch\Model\Adapter\FieldMapperInterface" not found

### ISSUE THREAD

**Issue by stefanskotte** [zepgram/module-disable-search-engine#18]
Running composer require:

```
[magdev@cp www]$ composer require zepgram/module-disable-search-engine

./composer.json has been updated
Running composer update zepgram/module-disable-search-engine
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Lock file operations: 1 install, 0 updates, 4 removals
  - Removing magento/module-elasticsearch (101.0.5)
  - Removing magento/module-elasticsearch-6 (100.4.5)
  - Removing magento/module-elasticsearch-7 (100.4.5)
  - Removing magento/module-inventory-elasticsearch (1.2.2)
  - Locking zepgram/module-disable-search-engine (0.2.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 1 update, 4 removals
  - Downloading aws/aws-sdk-php (3.304.5)
  - Downloading zepgram/module-disable-search-engine (0.2.2)
  - Removing magento/module-inventory-elasticsearch (1.2.2)
  - Removing magento/module-elasticsearch-7 (100.4.5)
  - Removing magento/module-elasticsearch-6 (100.4.5)
  - Removing magento/module-elasticsearch (101.0.5)
  - Upgrading aws/aws-sdk-php (3.304.4 => 3.304.5): Extracting archive
  - Installing zepgram/module-disable-search-engine (0.2.2): Extracting archive
  - Installing nathanjosiah/magento2-layout-debugger (dev-master 5b2128e): Extracting archive
Removing Magento/InventoryElasticsearch
Removing Magento/Elasticsearch7
Removing Magento/Elasticsearch6
Removing Magento/Elasticsearch
Package facebook/facebook-for-magento2 is abandoned, you should avoid using it. Use meta/meta-for-magento2 instead.
Package fgrosse/phpasn1 is abandoned, you should avoid using it. No replacement was suggested.
Package laminas/laminas-zendframework-bridge is abandoned, you should avoid using it. No replacement was suggested.
Package mageplaza/module-cron-schedule is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Package sebastian/phpcpd is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
128 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../ampersand,../../magento/magento-coding-standard,../../phpcompatibility/php-compatibility
Found 5 security vulnerability advisories affecting 2 packages.
Run "composer audit" for a full list of advisories.
Using version ^0.2.2 for zepgram/module-disable-search-engine
[magdev@cp www]$
[magdev@cp www]$ bin/magento module:enable Zepgram_DisableSearchEngine
The following modules have been enabled:
- Zepgram_DisableSearchEngine

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:enable' with the --clear-static-content option to clear them.
```

The setup:upgrade command worked fine.

Then setup:di:compile throws this error:

`Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 94.0 MiBInterface "Magento\Elasticsearch\Model\Adapter\FieldMapperInterface" not found#0 /home/magdev/www/vendor/composer/ClassLoader.php(576): include()
#1 /home/magdev/www/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/magdev/www/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#4 /home/magdev/www/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#5 /home/magdev/www/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#6 /home/magdev/www/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#7 /home/magdev/www/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /home/magdev/www/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#9 /home/magdev/www/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#10 /home/magdev/www/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
#11 /home/magdev/www/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#12 /home/magdev/www/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#13 /home/magdev/www/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#14 /home/magdev/www/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}`

I also tried to dump the autoload in composer, but the error persists.

**Comment by zepgram** [comment]
Are you running it on Magento 2.4.7 ? The module is not compatible yet with the latest version.

**Comment by stefanskotte** [comment]
Sorry, I forgot - it's 2.4.5-p7.

**Comment by zepgram** [comment]
The error in compilation refers to module "Magento\Elasticsearch" which is normally uninstalled by my module.

Could you run these command: 
```
rm -rf vendor/
rm -rf generated/code/
composer install
bin/magento setup:di:compile
```

**Comment by stefanskotte** [comment]
Ok. I have tried re-running the module installation:

```
./composer.json has been updated
Running composer update zepgram/module-disable-search-engine
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Lock file operations: 1 install, 0 updates, 4 removals
  - Removing magento/module-elasticsearch (101.0.5)
  - Removing magento/module-elasticsearch-6 (100.4.5)
  - Removing magento/module-elasticsearch-7 (100.4.5)
  - Removing magento/module-inventory-elasticsearch (1.2.2)
  - Locking zepgram/module-disable-search-engine (0.2.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 4 removals
  - Removing magento/module-inventory-elasticsearch (1.2.2)
  - Removing magento/module-elasticsearch-7 (100.4.5)
  - Removing magento/module-elasticsearch-6 (100.4.5)
  - Removing magento/module-elasticsearch (101.0.5)
  - Installing zepgram/module-disable-search-engine (0.2.2): Extracting archive
Removing Magento/InventoryElasticsearch
Removing Magento/Elasticsearch7
Removing Magento/Elasticsearch6
Removing Magento/Elasticsearch
Package facebook/facebook-for-magento2 is abandoned, you should avoid using it. Use meta/meta-for-magento2 instead.
Package fgrosse/phpasn1 is abandoned, you should avoid using it. No replacement was suggested.
Package laminas/laminas-zendframework-bridge is abandoned, you should avoid using it. No replacement was suggested.
Package mageplaza/module-cron-schedule is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Package sebastian/phpcpd is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
128 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../ampersand,../../magento/magento-coding-standard,../../phpcompatibility/php-compatibility
Found 5 security vulnerability advisories affecting 2 packages.
Run "composer audit" for a full list of advisories.
Using version ^0.2.2 for zepgram/module-disable-search-engine
```

Unfortunately, it does exactly the same thing (did rm -rf vendor, generated code, composer install):

```
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 94.0 MiBInterface "Magento\Elasticsearch\Model\Adapter\FieldMapperInterface" not found#0 /home/magdev/www/vendor/composer/ClassLoader.php(576): include()
#1 /home/magdev/www/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/magdev/www/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#4 /home/magdev/www/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#5 /home/magdev/www/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
#6 /home/magdev/www/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
#7 /home/magdev/www/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /home/magdev/www/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
#9 /home/magdev/www/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
#10 /home/magdev/www/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
#11 /home/magdev/www/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#12 /home/magdev/www/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#13 /home/magdev/www/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
#14 /home/magdev/www/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}
```

**Comment by stefanskotte** [comment]
I have tried removing an unused amasty elasticsearch-pro module as well, no change.

**Comment by stefanskotte** [comment]
Just did a bit more investigating here, seems like the amasty module could be the cause of it:

```
amasty/xsearch/Model/Elasticsearch/FieldMapper.php:use Magento\Elasticsearch\Model\Adapter\FieldMapperInterface;
amasty/xsearch/Model/Elasticsearch/FieldMapper.php:class FieldMapper implements FieldMapperInterface
amasty/shopby/Plugin/Elasticsearch/Model/Adapter/AdditionalFieldMapper.php:            if (is_object($fieldType) && ($fieldType instanceof AdditionalFieldMapperInterface)) {
amasty/shopby/Plugin/Elasticsearch/Model/Adapter/AdditionalFieldMapper.php:            if ($filedMapper instanceof AdditionalFieldMapperInterface) {
amasty/shopby/Plugin/Elasticsearch/Model/Adapter/AdditionalFieldMapper.php:            if ($filedMapper instanceof AdditionalFieldMapperInterface) {
amasty/shopby/Plugin/Elasticsearch/Model/Adapter/AdditionalFieldMapperInterface.php:interface AdditionalFieldMapperInterface
amasty/shopby/Plugin/Elasticsearch/Model/Adapter/FieldMapper/OnSale.php:use Amasty\Shopby\Plugin\Elasticsearch\Model\Adapter\AdditionalFieldMapperInterface;
amasty/shopby/Plugin/Elasticsearch/Model/Adapter/FieldMapper/OnSale.php:class OnSale implements AdditionalFieldMapperInterface
amasty/shopby/Plugin/Elasticsearch/SearchAdapter/Filter/Builder/RangePlugin.php:     * @var \Magento\Elasticsearch\Model\Adapter\FieldMapperInterface
amasty/shopby/Plugin/Elasticsearch/SearchAdapter/Filter/Builder/RangePlugin.php:     * @return \Magento\Elasticsearch\Model\Adapter\FieldMapperInterface
```

Let me try to get rid of all references the module and retry.

**Comment by stefanskotte** [comment]
Well, I hadn't removed the amasty elasticsearch module correctly above (typo), so now its gone and I have another dependency on Elasticsearch, so maybe its just not going to work for me as we need the shopby extension.

```
Compilation was started.
Area configuration aggregation... 5/9 [===============>------------]  55% 26 secs 406.0 MiB
In ClassReader.php line 57:

  Impossible to process constructor argument Parameter #0 [ <required> Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\TotalRecordsR
  esolverFactory $elasticResolverFactory ] of Amasty\Shopby\Model\ResourceModel\Fulltext\Collection\TotalRecordsResolver class


In GetParameterClassTrait.php line 34:

  Class "Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\TotalRecordsResolverFactory" does not exist


setup:di:compile
```

**Comment by zepgram** [comment]
Yes, if you have a module who depends on it you need to override it or
remove it from your dependency but there is no other choice.

If an extension effectively rely on elastic search, it means you are using
the search at a certain point.

So if you doesn't use the search, then you should be able to override
without breaking change.

Le mer. 22 mai 2024, 11:41, Stefan Skotte ***@***.***> a
écrit :

**Comment by stefanskotte** [comment]
Well to be honest we use an external search provider for all things search - but apparently amasty shopby uses som elasticsearch stuff, which seems odd.

I will see if I can override that and have it working still.

Thanks for the help so far :)

**Comment by stefanskotte** [comment]
Please close as it's related to 3rd party module.
